name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Menjalankan setiap jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update README
        uses: charmbracelet/readme-scribe@master
        with:
          template: "readme.tpl"
          write: "README.md"
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
