name: Update WakaTime Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          SHOW_TITLE: "true"
          TIME_ZONE: "Asia/Jakarta"
          SHOW_LANG_STATS: "true"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "false"
          SHOW_OS: "false"
          SHOW_LINES_OF_CODE: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_DAYS_OF_WEEK: "false"
          SHOW_SHORT_INFO: "false"
