name: Update WakaTime Gist

on:
  schedule:
    # Menjalankan setiap 30 menit
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          SHOW_TITLE: "true"
          BLOCKS: " ⣀⣄⣆⣇⣧⣷⣾⣿"
          TIME_ZONE: "Asia/Jakarta"
